---
- name: ansible using condition
  hosts: all
  become: true
  vars_prompt:
    - name: my_number
      prompt: please enter the number
      private: false
  tasks:
    - name: print this if less than 10
      ansible.builtin.debug:
        msg: " given {{ my_number }} is less then 10"
      when:  my_number  < 10 