---
- name: user exist or not
  hosts: all
  become: true
  tasks:
    - name: check the user exist or not
      ansible.builtin.command: id jagadish
      register: user
      ignore_errors: true

    - name: print the user 
      ansible.builtin.debug:
        msg: "user information is {{ user }}"

    - name: creating user 
      ansible.builtin.command: useradd jagadish
      when: user.rc != 0