---
- name: ansible loops
  hosts: all
  become: true
  tasks: 
    - name: installing packages using loops
      ansible.builtin.package:
        name: "{{ item.name }}"
        state: "{{ item.present }}"
      loop:
        - {name: 'postfix', state: 'present'}
        - {name: 'mysql', state: 'present'}
