---
- name: ansible loops
  hosts: all
  become: true
  tasks: 
    - name: installing packages using loops
      ansible.bultin.yum:
        name: "{{ item }}"
        state: presnet
      loop:
        - mysql
        - nginx
        - maven
