---
- name: ansible loops
  hosts: all
  become: true
  tasks: 
    - name: installing packages using loops
      ansible.bultin.package:
        name: {{ item }}
        state: presnet
      loop:
        - httpd
        - nginx
        - maven
